spring.application.name=be_accesa

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/CV_Matcher
spring.datasource.username=postgres
spring.datasource.password=changeme

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
